### ISSUE TITLE
Not Compatible with Wayland's Security

### ISSUE THREAD

**Issue by nmcbride** [AmberSahdev/Open-Interface#16]
On Wayland systems, the app needs to trigger the system dialog to grant permissions to it to capture the screen.

```
Traceback (most recent call last):
  File "app/app.py", line 5, in <module>
    from core import Core
  File "/tmp/_MEIOf6fGB/core.py", line 7, in <module>
    from interpreter import Interpreter
  File "/tmp/_MEIOf6fGB/interpreter.py", line 5, in <module>
    import pyautogui
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pyautogui/__init__.py", line 246, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mouseinfo/__init__.py", line 223, in <module>
  File "Xlib/display.py", line 80, in __init__
  File "Xlib/display.py", line 62, in __init__
  File "Xlib/protocol/display.py", line 129, in __init__
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
[2281152] Failed to execute script 'app' due to unhandled exception!

```

**Comment by mak448a** [comment]
If this helps, I think you need to use pipewire to do screen sharing.

**Comment by DanBoyDan** [comment]
I have similar issue. pipewire is installed and enabled on my 22.04 machine and still it is not running
