### ISSUE TITLE
Unhendled exeption script

### ISSUE THREAD

**Issue by BurHAN3508** [AmberSahdev/Open-Interface#25]
![resim](https://github.com/user-attachments/assets/516429f1-3814-4b72-bccc-ee1b03577b09)

**Comment by BurHAN3508** [comment]
Traceback (most recent call last):
  File "app\app.py", line 74, in <module>
  File "app\app.py", line 39, in __init__
  File "C:\Users\burha\AppData\Local\Temp\_MEI76882\core.py", line 22, in __init__
    self.llm = LLM()
               ^^^^^
  File "C:\Users\burha\AppData\Local\Temp\_MEI76882\llm.py", line 59, in __init__
    self.model = ModelFactory.create_model(self.model_name, base_url, api_key, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\burha\AppData\Local\Temp\_MEI76882\models\factory.py", line 13, in create_model
    raise ValueError(f'Unsupported model type {model_name}. Create entry in app/models/')
ValueError: Unsupported model type Qwen/Qwen2.5-Coder-32B-Instruct. Create entry in app/models/

**Comment by AmberSahdev** [comment]
Fixed some of this in the new version with better UI for error reporting. Check it out!
